# Hold 'a' to activate motion layer, which maps arrows and
# other navigation to the right hand, and some mods to the
# left hand.

device_name = "AT Translated Set 2 keyboard"

[[dual_role]]
input = "KEY_Z"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_Z"]

[[dual_role]]
input = "KEY_SLASH"
hold = ["KEY_RIGHTCTRL"]
tap = ["KEY_SLASH"]

[[dual_role]]
input = "KEY_SLASH"
hold = ["KEY_RIGHTCTRL"]
tap = ["KEY_SLASH"]

[[remap]]
input = ["KEY_CAPSLOCK"]
output = ["KEY_ESC"]

[[dual_role]]
input = "KEY_A"
hold = ["KEY_COFFEE"]
tap = ["KEY_A"]

[[remap]]
input = ["KEY_COFFEE", "KEY_F"]
output = ["KEY_COFFEE", "KEY_LEFTCTRL"]

[[remap]]
input = [ "KEY_COFFEE", "KEY_D"]
output = ["KEY_COFFEE", "KEY_LEFTSHIFT"]

[[remap]]
input = ["KEY_COFFEE", "KEY_J"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_COFFEE", "KEY_K"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_COFFEE", "KEY_L"]
output = ["KEY_RIGHT"]

[[remap]]
input = ["KEY_COFFEE", "KEY_I"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_COFFEE", "KEY_U"]
output = ["KEY_PAGEUP"]

[[remap]]
input = ["KEY_COFFEE", "KEY_O"]
output = ["KEY_PAGEDOWN"]

[[remap]]
input = ["KEY_COFFEE", "KEY_H"]
output = ["KEY_BACKSPACE"]

[[remap]]
input = ["KEY_COFFEE", "KEY_SEMICOLON"]
output = ["KEY_DELETE"]

[[remap]]
input = ["KEY_COFFEE", "KEY_COMMA"]
output = ["KEY_HOME"]

[[remap]]
input = ["KEY_COFFEE", "KEY_DOT"]
output = ["KEY_END"]
